### ISSUE TITLE
Create conda-recipe

### ISSUE THREAD

**Issue by tiffmay** [skyworksinc/skillbridge#2]
Here's how the about section looks now.  Let's update the other fields.

```yaml
about:
  home: "https://github.com/unihd-cag/skillbridge"
  license: "GNU Lesser General Public v3 (LGPLv3)"
  license_family: LGPL
  license_file: 
  summary: "A seamless Python remote bridge to Cadence's Skill in Virtuoso"
  doc_url: 
  dev_url: 
```

- [x] Add doc url as https://unihd-cag.github.io/skillbridge/
- [x] add dev_url as the repo URL, https://github.com/unihd-cag/skillbridge
- [x] Change home to the doc url
- [x] Update skill init file to sopy over server python file.

Discussed in https://github.com/skyworksinc/IDS-skill/issues/10
